allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  '@tsparticles/engine': true
  esbuild: true
  msw: true
  nx: true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
autoInstallPeers: true
packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/*/*'
  - 'packages/*'
