import type { Category } from '@einvoice/types';

export const categories: Category[] = [
  {
    id: 'cat-001',
    name: 'Khai vị',
    sortOrder: 1,
    timeStart: null,
    timeEnd: null,
    status: 'active',
    itemCount: 4,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'cat-002',
    name: 'Món chính',
    sortOrder: 2,
    timeStart: null,
    timeEnd: null,
    status: 'active',
    itemCount: 6,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'cat-003',
    name: 'Đồ uống',
    sortOrder: 3,
    timeStart: null,
    timeEnd: null,
    status: 'active',
    itemCount: 5,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'cat-004',
    name: 'Tráng miệng',
    sortOrder: 4,
    timeStart: null,
    timeEnd: null,
    status: 'active',
    itemCount: 3,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'cat-005',
    name: 'Điểm tâm',
    sortOrder: 5,
    timeStart: '06:00',
    timeEnd: '10:00',
    status: 'active',
    itemCount: 3,
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'cat-006',
    name: 'Combo đặc biệt',
    sortOrder: 6,
    timeStart: null,
    timeEnd: null,
    status: 'inactive',
    itemCount: 0,
    createdAt: '2026-03-15T10:00:00Z',
  },
];
