import type { RestaurantTable } from '@einvoice/types';

export const tables: RestaurantTable[] = [
  // Tầng trệt
  {
    id: 'tbl-001',
    areaId: 'area-001',
    areaName: 'Tầng trệt',
    name: 'T1',
    capacity: 4,
    status: 'available',
    qrToken: 'hmac_t1_abc123',
    sessionId: null,
  },
  {
    id: 'tbl-002',
    areaId: 'area-001',
    areaName: 'Tầng trệt',
    name: 'T2',
    capacity: 4,
    status: 'occupied',
    qrToken: 'hmac_t2_def456',
    sessionId: 'sess-001',
  },
  {
    id: 'tbl-003',
    areaId: 'area-001',
    areaName: 'Tầng trệt',
    name: 'T3',
    capacity: 6,
    status: 'billing',
    qrToken: 'hmac_t3_ghi789',
    sessionId: 'sess-002',
  },
  {
    id: 'tbl-004',
    areaId: 'area-001',
    areaName: 'Tầng trệt',
    name: 'T4',
    capacity: 2,
    status: 'available',
    qrToken: 'hmac_t4_jkl012',
    sessionId: null,
  },
  {
    id: 'tbl-005',
    areaId: 'area-001',
    areaName: 'Tầng trệt',
    name: 'T5',
    capacity: 8,
    status: 'cleaning',
    qrToken: 'hmac_t5_mno345',
    sessionId: null,
  },
  {
    id: 'tbl-006',
    areaId: 'area-001',
    areaName: 'Tầng trệt',
    name: 'T6',
    capacity: 4,
    status: 'occupied',
    qrToken: 'hmac_t6_pqr678',
    sessionId: 'sess-003',
  },

  // Lầu 1
  {
    id: 'tbl-007',
    areaId: 'area-002',
    areaName: 'Lầu 1',
    name: 'L1',
    capacity: 4,
    status: 'available',
    qrToken: 'hmac_l1_stu901',
    sessionId: null,
  },
  {
    id: 'tbl-008',
    areaId: 'area-002',
    areaName: 'Lầu 1',
    name: 'L2',
    capacity: 6,
    status: 'occupied',
    qrToken: 'hmac_l2_vwx234',
    sessionId: 'sess-004',
  },
  {
    id: 'tbl-009',
    areaId: 'area-002',
    areaName: 'Lầu 1',
    name: 'L3',
    capacity: 4,
    status: 'available',
    qrToken: 'hmac_l3_yza567',
    sessionId: null,
  },
  {
    id: 'tbl-010',
    areaId: 'area-002',
    areaName: 'Lầu 1',
    name: 'L4',
    capacity: 2,
    status: 'billing',
    qrToken: 'hmac_l4_bcd890',
    sessionId: 'sess-005',
  },
  {
    id: 'tbl-011',
    areaId: 'area-002',
    areaName: 'Lầu 1',
    name: 'L5',
    capacity: 4,
    status: 'available',
    qrToken: 'hmac_l5_efg123',
    sessionId: null,
  },

  // Sân vườn
  {
    id: 'tbl-012',
    areaId: 'area-003',
    areaName: 'Sân vườn',
    name: 'SV1',
    capacity: 6,
    status: 'occupied',
    qrToken: 'hmac_sv1_hij456',
    sessionId: 'sess-006',
  },
  {
    id: 'tbl-013',
    areaId: 'area-003',
    areaName: 'Sân vườn',
    name: 'SV2',
    capacity: 8,
    status: 'available',
    qrToken: 'hmac_sv2_klm789',
    sessionId: null,
  },
  {
    id: 'tbl-014',
    areaId: 'area-003',
    areaName: 'Sân vườn',
    name: 'SV3',
    capacity: 4,
    status: 'cleaning',
    qrToken: 'hmac_sv3_nop012',
    sessionId: null,
  },
  {
    id: 'tbl-015',
    areaId: 'area-003',
    areaName: 'Sân vườn',
    name: 'SV4',
    capacity: 10,
    status: 'available',
    qrToken: 'hmac_sv4_qrs345',
    sessionId: null,
  },

  // Phòng VIP
  {
    id: 'tbl-016',
    areaId: 'area-004',
    areaName: 'Phòng VIP',
    name: 'VIP1',
    capacity: 12,
    status: 'occupied',
    qrToken: 'hmac_vip1_tuv678',
    sessionId: 'sess-007',
  },
  {
    id: 'tbl-017',
    areaId: 'area-004',
    areaName: 'Phòng VIP',
    name: 'VIP2',
    capacity: 20,
    status: 'available',
    qrToken: 'hmac_vip2_wxy901',
    sessionId: null,
  },
];
